#!/bin/bash

# Check for install
which git > /dev/null
if [[ $? != 0 ]]
then
	echo "git is not installed!"
	exit 1
fi

# Check for minimum version
GITVER=$(git --version | awk '{print $3}' | awk -F'.' '{print $1"."$2}')
GITMIN="2.25"
if (( $(echo "$GITVER < $GITMIN" | bc -l) ))
then
	echo "git version is too low! Update now!"
	echo "Your version: $GITVER | Minimum version required: $GITMIN"
	echo "sudo add-apt-repository ppa:git-core/ppa"
	echo "sudo apt update"
	echo "sudo apt install git"
	exit 1
fi

# Get current branch
TREEBRANCH=$(git branch --show-current)

if [[ "$TREEBRANCH" =~ ^(main|master) ]]
then
	git status -s | grep -E "^ M" > /dev/null
	if [[ $? == 0 ]]
	then
		echo "You are on the main/master branch, HOWEVER changes have been detected!"
		read -p "Would you like to create a new branch to move the changes to? (y/n): " ANS
		if [[ "$ANS" =~ ^(y|Y)$ ]]
		then
			read -p "Enter a new branch name (letters, numbers and dashes only): " NB
			if [[ "$NB" =~ ^[-A-Za-z0-9]+$ ]]
			then
				git switch -c "$NB"
				echo "Run `gitgit 'commit description'` to push the changes" 
			else
				echo "Invalid Branch Name, exiting! You still have changes on your main/master branch!"
				exit 1
			fi
		else
			echo "Leaving changes on the main/master branch alone and exiting!"
			exit 1
		fi
	else
		echo "You are on the main branch, exiting..."
		exit 1
	fi
elif [[ "$1" == -d ]]
then
	THEBRANCH=$(git branch | sed 's/ //g' | grep -E "^(main|master)$" | head -1)
	echo "Switching to $THEBRANCH, updating and DELETING $TREEBRANCH"
	git checkout $THEBRANCH
	git pull
	git fetch --prune
	git branch -d $TREEBRANCH
else
	echo "On Branch: $TREEBRANCH"
	git add .

	if [ -z "$1" ]
	then
		COMMITNOW="Generic change made on $(date)"
	else
		COMMITNOW="$1"
	fi

	git commit -m "$COMMITNOW"
	git push origin $TREEBRANCH

	echo "Thanks for using gitgit! Don't forget to delete this branch when finished: gitgit -d"
fi
